config/routes.rb
Rails.application.routes.draw do
	resources :movies
  root to: "movies#index"
	get 'movies/filter/:country', to:"movies#filter", as: :filter
  get 'hakkinda', to: "pages#about", as: :about
  get 'iletisim', to: "pages#contact", as: :contact

end

app/models/movie.rb
class Movie < ActiveRecord::Base
    validates :title, presence: true
    validates :description, presence: true
    validates :date, numericality: true
    has_attached_file :image, styles: { medium: "182x268>", small: "150x150>" }
	  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :find_movie, only:[:show, :edit, :update, :destroy]

	def show
		@lastmovies = Movie.last(6)
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new movie_params

		if @movie.save
			redirect_to @movie , notice: "Başarılya Oluşturuldu"
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @movie.update(movie_params)
			redirect_to @movie , notice: "Film Güncellendi"
		else
			render 'edit'
		end
	end

	def index
		@movies = Movie.all
	end

	def destroy
		@movie.destroy
		redirect_to root_path, notice: "Başarıyla Silindi"
	end

	def filter
		@movies = Movie.all.where(country: params[:country])
	end


	def movie_params
		params.require(:movie).permit(:title, :description, :date, :director, :country, :image)
	end

	def find_movie
		@movie = Movie.find(params[:id])
	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> Filmci</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Filmci</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= active_link_to 'Anasayfa', root_path, :wrap_tag => :li %>
        <%= active_link_to 'Hakkkında', about_path, :wrap_tag => :li %>
        <%= active_link_to 'İletişim', contact_path, :wrap_tag => :li %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= active_link_to 'Yeni Film Ekle', new_movie_path, :wrap_tag => :li %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <% if flash.notice %>
  <div class="alert alert-info" role="alert">
    <%= flash.notice %>
  </div>
  <% end %>
  
	<%= yield %>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<div class="row">


    <%= form_for @movie do |m| %>

    <div class="col-md-4">

      <%= label_tag(:movie_title, "Film Adı") %>
      <%= m.text_field :title, class: "form-control" %>

      <%= label_tag(:movie_description, "Açıklama") %>
      <%= m.text_area :description, class: "form-control", style: "resize: none;" %>

      <%= label_tag(:movie_image, "Poster") %>
      <%= m.file_field :image, class: "form-control" %>

      <%= label_tag(:movie_date, "Yapım Yılı") %>
      <%= m.number_field :date, class: "form-control" %>

      <%= label_tag(:movie_director, "Yönetmen") %>
      <%= m.text_field :director, class:"form-control" %>

      <%= label_tag(:movie_country, "Ülke") %>
      <%= m.text_field :country, class: "form-control" %>
        <br />
      <%= submit_tag "Gönder", class: "btn btn-success" %>
    </div>

    <div class="col-md-6">
      <% if @movie.errors.any? %>
        <h2><%= pluralize(@movie.errors.count, "error") %></h2>

          <% @movie.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
              <%= msg %>
            </div>
        <% end %>

      <% end %>
    </div>

    <% end %>

</div>

app/views/movies/_list.html.erb
<% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= link_to (image_tag movie.image.url(:medium)), movie %>

          <div class="caption">
            <h3><%= link_to movie.title, movie %></h3>
            <p><%= movie.description.truncate_words(6) %></p>
          </div>
        </div>
      </div>
<% end %>

app/views/movies/edit.html.erb
<% content_for :title, "Düzenle: #{@movie.title} , " %>

<%= render 'form' %>

app/views/movies/filter.html.erb
<% if @movies.length > 0 %>
    <% content_for :title, "Filtre Sonucu - " %>
    <h4>Film Listesi</h4>
    <div class="row">
     <%= render 'list' %>
    </div>
<% else %>
<h2>Film Bulunamadı</h2>
<% end %>

app/views/movies/index.html.erb
<% content_for :title, "Filmler - " %>
<h4>Film Listesi</h4>
<div class="row">
  <%= render 'list' %>
</div>

app/views/movies/new.html.erb
<% content_for :title, "Yeni Ekle , " %>
<%= render 'form' %>

app/views/movies/show.html.erb
<% content_for :title, "#{@movie.title} - " %>
<div class="row">
	<div class="col-xs-6 col-md-3">
		<%= image_tag @movie.image.url(:medium) %>
	</div>
	<div class="col-xs-6 col-md-9">
		<p><b>Film Adı: </b><%= @movie.title %></p>
		<p><b>Açıklama: </b><%= @movie.description %></p>
		<p><b>Yıl:</b><%= @movie.date %></p>
		<p><b>Ülke:</b><%= link_to @movie.country, filter_path(@movie.country) %></p>
		<p><b>Yönetmen: </b><%= @movie.director %></p>

		<hr />
		<%= link_to 'Düzenle', edit_movie_path , class: "btn btn-warning" %>
		<%= link_to "Sil", @movie , method: :delete, data: {confirm: 'Emin misin'}, class: "btn btn-danger" %>
	</div>

</div>

<div class="row">
	<div class="col-md-12">
		<hr>
		<h3>Son 6 Film</h3>
		<% @lastmovies.each do |movie| %>
		  <div class="col-xs-4 col-md-2">
		  	<%= link_to (image_tag movie.image.url(:small) ), movie, class: 'thumbnail' %>
		  </div>
		<% end %>
	</div>
</div>

app/views/pages/about.html.erb
<% content_for :title, "Hakkımızda - " %>
<h1>Hakkında Sayfası</h1>

app/views/pages/contact.html.erb
<% content_for :title, "İletişim - " %>
<h1>İletişim Sayfası</h1>

app/views/pages/home.html.erb
<h1>Anasayfa</h1>

<h4>Film Listesi</h4>
<div class="row">
<% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
         
          <div class="caption">
            <h3><%= link_to movie.title, movie %></h3>
            <p><%= movie.description %></p>
          </div>
        </div>
      </div>
<% end %>
</div>